# required paths
path_dataset: '/home/hamish/Documents/robohop/hm3d/'
path_models: ''
path_results: '/home/hamish/Documents/robohop/results/tango/reconfirm/'  #'/storage/results/collaborations/robohop/results/new/'

# start and stop indexes for runs
start_index: 0
end_index: 108
# running from list of winners or failure or no good
run_list: '' #'winners'  #  ['', 'winners', 'failures', 'no_good']
path_run: '' # '/storage/results/collaborations/robohop/results/val/hard/20240912-17-53-21_robohop+_topological'

# simulator params
split: 'val'  # train, val
max_steps: 250
threshold_goal_distance: 1.0  # in meters
max_start_distance: 'hard'  # ['easy', 'hard', 'full']

# controller and mapping params
method: 'pixnav'
segmentor: 'fastsam' # [sim, fastsam]
goal_source: 'topological'  # [gt_metric, gt_topological, topological]
infer_depth: 1
infer_traversable: 1

# logging and display
log_robot: 1
plot: 0
dump_episode_images: 0

debug: 0