# required paths
path_dataset: '/storage/Datasets/AIhabitat/robohop/navigation'
path_models: ''
path_results: '/storage/results/collaborations/robohop/results/new/'

# start and stop indexes for runs
start_index: 0
end_index: 200
# running from list of winners or failure or no good
run_list: '' #'winners'  #  ['', 'winners', 'failures', 'no_good']
path_run: '' # '/storage/results/collaborations/robohop/results/val/hard/20240912-17-53-21_robohop+_topological'

# simulator params
split: 'val'  # train, val
max_steps: 500
threshold_goal_distance: 1.0  # in meters
max_start_distance: 'hard'  # ['easy', 'hard', 'full']

# controller and mapping params
method: 'robohop+'
segmentor: 'sim' # [sim, fastsam]
goal_source: 'gt_metric'  # [gt_metric, gt_topological, topological]
infer_depth: 0
infer_traversable: 0

# logging and siplay
log_robot: 1
plot: 0
dump_episode_images: 0

debug: 0