# required paths
path_dataset: '/home/stefan/projects/tango/dataset'
path_models: 'third_party/models/'
path_results: '/home/stefan/projects/tango/results'

# start and stop indexes for runs
start_index: 0
end_index: 200
steps_index: 1
# running from list of winners or failure or no good
run_list: '' #'winners'  #  ['', 'winners', 'failures', 'no_good']
path_run: '' # '/storage/results/collaborations/robohop/results/val/hard/20240912-17-53-21_robohop+_topological'

# simulator params
split: 'val'  # train, val
max_steps: 500
threshold_goal_distance: 1.0  # in meters
max_start_distance: 'easy'  # ['easy', 'hard', 'full']
sim:
  hfov: 120
  width: 320
  height: 240
  sensor_height: 0.4 # [0.4, 1.31, 1.5]


# controller and mapping params
method: 'tango'
segmentor: 'sim' # [sim, fastsam]
goal_source: 'gt_metric'  # [gt_metric, gt_topological, topological]
infer_depth: 0
infer_traversable: 0

# tango's visualization panel
plot: 1
save_vis: False
dump_episode_images: 0
#log_robot: 1
#dump_episode_images: 0

debug: 0